services:
  openvpn:
    image: ghcr.io/huihuimoe/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
    volumes:
      - ./conf:/etc/openvpn
    restart: unless-stopped
